### ISSUE TITLE
mac 64运行报错

### ISSUE THREAD

**Issue by CLAY-git** [FynnFbc/TunnelProxyPool#1]
goroutine 44 [running]:
main.get_gkydaili()
	D:/GoLang/TunnelProxyPool/src/spider.go:159 +0x205
created by main.spiderRun
	D:/GoLang/TunnelProxyPool/src/spider.go:55 +0x194

**Comment by VMCoud** [comment]
试试这个
下载地址：https://www.123pan.com/s/gat8Vv-jnNCh.html  提取码:2saV
